"""initial schema

Revision ID: fb3920a81f37
Revises: 
Create Date: 2026-06-07 22:13:04.780444
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3920a81f37'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('source_system', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_name'), ['name'], unique=False)

    op.create_table('compliance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('access', 'erasure', name='requesttype', native_enum=False), nullable=False),
    sa.Column('subject_ref', sa.String(length=200), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'completed', name='requeststatus', native_enum=False), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_requests_subject_ref'), ['subject_ref'], unique=False)

    op.create_table('data_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pii_category', sa.Enum('none', 'name', 'email', 'phone', 'national_id', 'address', 'date_of_birth', 'ip_address', 'credit_card', name='piicategory', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_fields_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('usage_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.Enum('consent', 'contract', 'legal_obligation', 'vital_interests', 'public_task', 'legitimate_interests', name='legalbasis', native_enum=False), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_agreements_dataset_id'), ['dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_agreements_dataset_id'))

    op.drop_table('usage_agreements')
    with op.batch_alter_table('data_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_fields_dataset_id'))

    op.drop_table('data_fields')
    with op.batch_alter_table('compliance_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_requests_subject_ref'))

    op.drop_table('compliance_requests')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_name'))

    op.drop_table('datasets')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
